name: Build PDF and release
on: push

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: solutions.tex
      - name: Get timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Draft ${{ env.TIMESTAMP }}
          files: Intro-to-QM/solutions.pdf
          draft: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}} 
          asset_path: ${{env.FILE_PATH}}${{env.FILE_NAME}}.pdf
          asset_name: ${{env.RESULT_NAME}}.pdf
          asset_content_type: application/pdf
